baseURL = 'https://intangiblematter.github.io'
languageCode = 'en-us'
title = 'IntangibleMatter'
theme = 'intangibletheme23'
enableGitInfo = true
[menu]
    [[menu.main]]
        name = "Home"
        pre = "home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Games"
        pre = "games"
        url = "https://intangiblematter.itch.io/"
        weight = 2
    [[menu.main]]
        name = "Blog"
        pre = "blog"
        url = "/blog/"
        weight = 3
	[[menu.main]]
		name = "Personal"
		pre = "personal"
		url = "/personal/"
		weight = 4



[permalinks]
    personal = '/personal/:year:month:day/:title/'
	blog = '/blog/:year:month:day/:title/'



[markup]
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ''
        hl_inline = false
        lineAnchors = ''
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        noHl = false
        style = 'fruity'
        tabWidth = 4
